variables:
  IMAGE_NAME: ilvlan549/genipa
  IMAGE_TAG: dle-1.0

stages:
  - test
  - build
  
run_tests:
  image: python:3.10-slim
  stage: test
  before_script:
    - apt-get update 
    - pip install -r requirements.txt
  script:
    - python -m pytest

build_image:
  image: docker:20.10.16
  stage: build
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG